### ISSUE TITLE
FOLON Downgrader on Nobara Linux cannot find dependencies present on the install.

### ISSUE THREAD

**Issue by AshtonSnapp** [Fallout-London/FOLON-FO4Downgrader#23]
Hello, I am trying to get Fallout London to work and have been encountering some issues running the downgrader for Linux. For some odd reason, it cannot find dependencies that are present on the drive.  (Directory path shortened to save space)

```shell
ashtons@destroyer:.../Linux-Downgrader/FOLON-Downgrader-Linux$$ ./FOLON-Downgrader
curl: /tmp/_MEIW80YPi/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /lib64/libcurl.so.4)
curl: /tmp/_MEIW80YPi/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /lib64/libcurl.so.4)
Error in sys.excepthook:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ModuleNotFoundError: No module named 'tkinter'

Original exception was:
Traceback (most recent call last):
  File "FOLON-Downgrader.py", line 927, in <module>
  File "FOLON-Downgrader.py", line 875, in main
  File "FOLON-Downgrader.py", line 49, in SetupFont
  File "zipfile.py", line 1253, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'FOLON-Downgrader-Files/overseer.zip'
[11926] Failed to execute script 'FOLON-Downgrader' due to unhandled exception!
ashtons@destroyer:.../Linux-Downgrader/FOLON-Downgrader-Linux$$ sudo dnf install ssl
[sudo] password for ashtons: 
Last metadata expiration check: 0:10:30 ago on Sun 28 Jul 2024 10:01:59 AM CDT.
No match for argument: ssl
Error: Unable to find a match: ssl
ashtons@destroyer:.../Linux-Downgrader/FOLON-Downgrader-Linux$$ sudo dnf install openssl
Last metadata expiration check: 0:10:37 ago on Sun 28 Jul 2024 10:01:59 AM CDT.
Package openssl-1:3.2.1-2.fc40.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
ashtons@destroyer:.../Linux-Downgrader/FOLON-Downgrader-Linux$ sudo dnf install python-tkinter
Last metadata expiration check: 0:10:52 ago on Sun 28 Jul 2024 10:01:59 AM CDT.
Package python3-tkinter-3.12.4-1.fc40.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
ashtons@destroyer:.../Linux-Downgrader/FOLON-Downgrader-Linux$ sudo dnf install curl
Last metadata expiration check: 0:10:52 ago on Sun 28 Jul 2024 10:01:59 AM CDT.
Package curl-8.6.0-8.fc40.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```

As you can see, all required dependencies are installed. But, for some reason, the application simply cannot find them. So it's unable to download a needed file, so the program just crashes. I am quite confused as to how I may proceed. This is the version available on Nexus Mods, for context.

**Comment by coffandro** [comment]
Try copying the things in run.sh into the terminal, might do it

**Comment by coffandro** [comment]
Would you kindly try the folowing @AshtonSnapp 
```
git clone https://github.com/Fallout-London/FOLON-FO4Downgrader.git && cd FOLON-FO4Downgrader && chmod +x Run.sh && ./Run.sh
```
