### ISSUE TITLE
Fedora/Nobara 40 depency issue

### ISSUE THREAD

**Issue by jabeston** [Fallout-London/FOLON-FO4Downgrader#4]
System Configuration:
Default Nobara 40 full upgraded

Steps to recreate:
Download password fix release
execute in terminal

```
> ./FOLON-Downgrader
curl: /tmp/_MEIfWxnoP/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /lib64/libcurl.so.4)
Traceback (most recent call last):
  File "FOLON-Downgrader.py", line 926, in <module>
  File "FOLON-Downgrader.py", line 874, in main
  File "FOLON-Downgrader.py", line 41, in SetupFont
  File "zipfile.py", line 1253, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'FOLON-Downgrader-Files/overseer.zip'
[10396] Failed to execute script 'FOLON-Downgrader' due to unhandled exception!
 ```

DNF shows
```
> sudo dnf install openssl
[sudo] password for XXXXXXXX: 
Last metadata expiration check: 0:02:13 ago on Wed 24 Jul 2024 04:13:46 PM CDT.
Package openssl-1:3.2.1-2.fc40.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```

**Comment by coffandro** [comment]
could you check the result of ```curl -v```?

**Comment by coffandro** [comment]
If you check in the subfolder `FOLON-Downgrader-Files` does a Fonts folder exist?

**Comment by jabeston** [comment]
Negative

**Comment by coffandro** [comment]
does
```
curl -sqL "https://dl.dafont.com/dl/?f=overseer" -o FOLON-Downgrader-Files/overseer.zip
```
work in that directory?

**Comment by jabeston** [comment]
It does

**Comment by coffandro** [comment]
and a overseer.zip file's oresent?

**Comment by jabeston** [comment]
Correct.

When running the release again after the curl command downloading overseer.zip

```
> ./FOLON-Downgrader
curl: /tmp/_MEIzn6UWV/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /lib64/libcurl.so.4)
xdg_toplevel@33: error 2: minimum width can't be bigger than the maximum width
The Wayland connection experienced a fatal error: Protocol error
```

**Comment by coffandro** [comment]
I've made a new version that *might* fix this, please remove the folder and try running this

**Comment by coffandro** [comment]
This might fix it but I have no idea https://github.com/Fallout-London/FOLON-FO4Downgrader/releases/tag/1.4.3

**Comment by jabeston** [comment]
Curl isssue resolved. Opening Wayland issue
