### ISSUE TITLE
Running on Linux Nobara

### ISSUE THREAD

**Issue by Dreamsword** [Fallout-London/FOLON-FO4Downgrader#46]
Getting this issue when running the tool(my fallout 4 is on steam) -

Traceback (most recent call last):
  File "/home/dreamsword/Downloads/FOLON-FO4Downgrader/./FOLON-Downgrader.py", line 39, in <module>
    Linux()
  File "/home/dreamsword/Downloads/FOLON-FO4Downgrader/LinuxDowngrader.py", line 146, in Linux
    with open(f"{Path}/SteamFiles/DepotsList.txt", "wb") as out_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/webbrowser.py", line 87, in open
    if browser.open(url, new, autoraise):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/webbrowser.py", line 270, in open
    raise Error("Bad 'new' parameter to open(); " +
webbrowser.Error: Bad 'new' parameter to open(); expected 0, 1, or 2, got wb
Please check dependencies from here https://github.com/Fallout-London/FOLON-FO4Downgrader/blob/main/LinuxDeps.md

**Comment by coffandro** [comment]
Oh I'll fix that but everything should be fine

**Comment by coffandro** [comment]
Fixed: 553be18d6ab66ef319b9d143a83e432cbd435dca
