### ISSUE TITLE
Spaces handling in Fallout 4 path broken

### ISSUE THREAD

**Issue by el8** [Fallout-London/FOLON-FO4Downgrader#48]
Running ./Run.sh I'm getting this exception in the end:
Downloading steam...
Traceback (most recent call last):
  File "/home/jang/src/git-trees/FOLON-FO4Downgrader/./FOLON-Downgrader.py", line 39, in <module>
    Linux()
  File "/home/jang/src/git-trees/FOLON-FO4Downgrader/LinuxDowngrader.py", line 36, in Linux
    os.mkdir(f"{Path}/SteamFiles")
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/fast/SteamLibrary/steamapps/common/Fallout\\ 4//SteamFiles'
Please check dependencies from here https://github.com/Fallout-London/FOLON-FO4Downgrader/blob/main/LinuxDeps.md

The `Fallout\\ 4` part looks odd. Also, when I'm entering the path the script does not accept the real escaped path:
```
./Run.sh 
What is the path to Fallout4?: /mnt/fast/SteamLibrary/steamapps/common/Fallout\ 4/
Please input a path
What is the path to Fallout4?: /mnt/fast/SteamLibrary/steamapps/common/Fallout 4  
Downloading steam...
```

**Comment by coffandro** [comment]
And you just input `/mnt/fast/SteamLibrary/steamapps/common/Fallout 4,` right?

**Comment by el8** [comment]
Yes, when I give the real path containing the escaped space it does accept it.

**Comment by coffandro** [comment]
And without the backslash?

**Comment by coffandro** [comment]
Hmm alr that's confusing, what does your *top app show about python and the script regarding network and cpu?

**Comment by el8** [comment]
I've tried again with the latest binary release instead of git head, no issues there.

**Comment by coffandro** [comment]
You're in the 0.00(and so on)001% then my friend, for most the binary dosen't work, also assume you're on an ubuntu based distro then lol
